_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 60
max_epochs: 80

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
