_target_: src.models.simple_reid_module.SimpleReIdLitModule

optimizer_options:
  optimizer: sgd
  lr: 0.001
  weight_decay: 0.0005
  scheduler:
    apply: True
    type: OneCycleLR
    max_lr: 0.0008
    num_epochs: 80
backbone: resnet34
stage: null
checkpoint_path: null
