_target_: src.models.simple_reid_module.SimpleReIdLitModule
backbone: resnet18

optimizer_options:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.0005
  scheduler:
    apply: False
    type: WarmupLR
    max_lr: 0.00035
    num_epochs: 70
