_target_: src.datamodules.city_flow_datamodule.CityFlowDataModule

data_dir: "data/AIC21_Track2_ReID"
batch_size: 64
num_workers: 12
pin_memory: False
val_fold: null

aug:
  apply: True
  horizontal_flip: True
  random_brightness_contrast: True
  shift_scale_rotate: True
  cutout: True

stage: null